### ISSUE TITLE
AutoLayout constraints and automatic label height adjustments

### ISSUE THREAD

**Issue by cognitiveflux** [SebastienThiebaud/STTweetLabel#121]
Consider the following two simple ASCII constraints where `[label]` refers to an instance of `UILabel` and the superview is the `contentView` of a `UITableViewCell`:

`"H:|-[label]-|"` and `"V:|-[label]-|"`

Without implementing `tableView:heightForRowAtIndexPath:` and using the above ASCII constraints with AutoLayout, the superview correctly adjusts its size based on the height of the child `UILabel` when `lineBreakMode = NSLineBreakByWordWrapping` and `numberOfLines = 0` and text with multiple lines is assigned to the label.

Simply changing `UILabel` to `STTweetLabel` results in AutoLayout not adjusting the height based on the content of the text.

Understanding that there is `suggestedFrameSizeToFitEntireStringConstraintedToWidth:`, I'm curious why an instance of `UILabel` and AutoLayout is able to calculate the height automatically but `STTweetLabel` is not?  I'm assuming AutoLayout calls a method in `UILabel` to get the adjusted height, but that method is missing in `STTweetLabel`?

**Comment by Reza-Rg** [comment]
The best solution that I find to solve this problem, was to use a hidden EditText, under STTweetLabel and add constrain to that DUMMY EditText.
For me, now it's working great! :)

**Comment by caofei10119** [comment]
@cognitiveflux the issue has been addressed?

**Comment by radhakrishnapai** [comment]
Hi. The issue still exists in calculating automaticheight. 
I set top bottom left and write constraints for my `STTweetAuto` label. The constant values for top and bottom were `8` and `9` in XIB. This changed to `5` each at runtime which caused unsatisfiable constraints issue. 
When I changed the class to `UILabel` everything works as expected.
